### ISSUE TITLE
Overlapping of Mobile Menu and Desktop Collapse Buttons Causes Sidebar Collapsing Issues

### ISSUE THREAD

**Issue by Thiwain** [Kiranism/react-shadcn-dashboard-starter#6]
- The mobile sidebar menu button and desktop collapse button sometimes both show up and overlap, which leads to weird sidebar behavior. When both buttons are visible, the sidebar collapsing can get unpredictable

**Comment by Kiranism** [comment]
> * The mobile sidebar menu button and desktop collapse button sometimes both show up and overlap, which leads to weird sidebar behavior. When both buttons are visible, the sidebar collapsing can get unpredictable

Hey, Migrate to shadcn sidebar.
